### ISSUE TITLE
Unregistered mailbox cannot send login link directly

### ISSUE THREAD

**Issue by bailaoshijiadao** [clarkwinkelmann/flarum-ext-passwordless#5]
Unregistered mailbox cannot send login link directly, 
the prompt is as shown below
Your login details were incorrect.
![1](https://user-images.githubusercontent.com/47207238/110106919-37ad0200-7de5-11eb-8dc5-d4a7ad5f6c47.png)

**Comment by clarkwinkelmann** [comment]
I don't understand what the issue is? Is that email present in the Flarum database?

What do you mean by unregistered mailbox? If the user is not yet registered in Flarum, they must click "Sign Up" to create their account. Only once they have an account they can use the email login. With the extension enabled, the password field is also removed from registration.

**Comment by bailaoshijiadao** [comment]
Can it be written as automatic account creation?

**Comment by clarkwinkelmann** [comment]
The problem is that you need to choose a username, so you would need to be directed to the SignUp modal anyway.

What I could do is that since "invalid credentials" automatically means unknown email, I could add a link to the error message that says "do you want to create an account?" or automatically open the SignUp modal after an error with email pre-filled.

Personally I don't have that use case, because this extension is used on a forum where user accounts are created in advance, and the users don't even know their usernames. This allows them logging in easily without having to setup a username and password.

If usernames are not important to your use case, then it would be possible to auto-generate a username for emails that don't exist, and replace account activation with the passwordless email. This last option is however quite far outside the original scope of this extension so I wouldn't implement this without someone sponsoring the feature.

**Comment by bailaoshijiadao** [comment]
automatically open the SignUp modal after an error with email pre-filled. This is a good idea

**Comment by clarkwinkelmann** [comment]
I have implemented the error message improvement in version 1.5.0

By default the text is identical to the one at the bottom of the modal. It can be customized using Linguist (`clarkwinkelmann-passwordless.forum.sign-up.error-try-signup`). The "invalid credentials" message is a separate message from core (`core.forum.log_in.invalid_login_message`)

![image](https://user-images.githubusercontent.com/5264300/204418260-978689ba-da23-45a8-8d53-f7f399aa41b3.png)

I'm not planning to add anything more advanced. Auto-generating usernames and other required fields added by extensions is too advanced for this extension.
